services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_HCAPTCHA_SITE_KEY: ${NEXT_PUBLIC_HCAPTCHA_SITE_KEY}
    container_name: biblio-app
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
    env_file:
      - .env.production
    volumes:
      - ./public/uploads:/app/public/uploads
    depends_on:
      db:
        condition: service_healthy
    
    networks:
      - biblio-network
      - nginx-proxy-manager_default

  db:
    image: postgres:16-alpine
    container_name: biblio-db
    restart: unless-stopped
    ports: 
        - "5432:5432"
    env_file:
      - .env.production
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lucas -d biblio_jouets"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - biblio-network

volumes:
  postgres_data:

networks:
  biblio-network:
    driver: bridge
  nginx-proxy-manager_default:
    external: true